// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Image is a Knative abstraction that encapsulates the interface by which Knative
 * components express a desire to have a particular image cached.
 */
export class Image extends pulumi.CustomResource {
    /**
     * Get an existing Image resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Image {
        return new Image(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:caching.internal.knative.dev/v1alpha1:Image';

    /**
     * Returns true if the given object is an instance of Image.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Image {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Image.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"caching.internal.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"Image" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec holds the desired state of the Image (from the client).
     */
    public readonly spec!: pulumi.Output<outputs.caching.v1alpha1.ImageSpec | undefined>;
    /**
     * Status communicates the observed state of the Image (from the controller).
     */
    public readonly status!: pulumi.Output<outputs.caching.v1alpha1.ImageStatus | undefined>;

    /**
     * Create a Image resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ImageArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "caching.internal.knative.dev/v1alpha1";
            resourceInputs["kind"] = "Image";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Image.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Image resource.
 */
export interface ImageArgs {
    apiVersion?: pulumi.Input<"caching.internal.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"Image">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec holds the desired state of the Image (from the client).
     */
    spec?: pulumi.Input<inputs.caching.v1alpha1.ImageSpecArgs>;
    /**
     * Status communicates the observed state of the Image (from the controller).
     */
    status?: pulumi.Input<inputs.caching.v1alpha1.ImageStatusArgs>;
}
