version: "3"

includes:
  plane-bot:
    taskfile: common/Taskfile.yml
    dir: plane-bot
    vars:
      NAME: plane-bot

tasks:
  deploy:
    desc: Deploy all functions
    cmds:
      - task: plane-bot:deploy-no-build
