version: 3

includes:
  terraform:
    taskfile: terraform/Taskfile.yml
    dir: terraform

  nixos:
    taskfile: nixos/Taskfile.yml
    dir: nixos

  projects:
    taskfile: pulumi/tasks/Taskfile.projects.yml
    dir: pulumi/projects

  base:
    taskfile: pulumi/tasks/Taskfile.base.yml
    dir: pulumi

  backup:
    taskfile: pulumi/tasks/Taskfile.backup.yml
    dir: pulumi

  migrate:
    taskfile: pulumi/tasks/Taskfile.migrate.yml
    dir: pulumi

tasks:
  etebase:manage:
    desc: Manage Etebase via Django CLI
    cmd: |
      pod=$(kubectl get pods -l app.kubernetes.io/name=etebase -o jsonpath="{.items[0].metadata.name}" -n etebase)
      kubectl exec -n etebase -c etebase -it $pod -- /etebase/manage.py {{.CLI_ARGS}}

  create-dashboard-token:*:
    vars:
      CONTEXT: "{{index .MATCH 0}}"
    desc: Create a token for the Kubernetes dashboard
    cmd: kubectl -n kubernetes-dashboard create token dashboard-account --duration=100000h --context={{.CONTEXT}}
