version: "3"

includes:
  projects:
    taskfile: Taskfile.projects.yml
    dir: ../projects
    internal: true

  backup:
    taskfile: Taskfile.backup.yml
    dir: ..
    internal: true

vars:
  DATABASES:
    - postgresql
    - mariadb
    - minio
  STATEFUL_APPS:
    - syncthing
    - n8n
    - sftpgo
    - etebase
  STATELESS_APPS:
    - vaultwarden
    - plane
    - ente
    - smtp-to-telegram
    - vpn
    - vpn-static

tasks:
  all:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
    desc: Migrate all projects from one cluster to another
    cmds:
      # 1. Up databases on the target
      - task: backup-and-up-databases:{{.SOURCE}}:{{.TARGET}}

      # 2. Migrate apps
      - task: apps:{{.SOURCE}}:{{.TARGET}}

      # 3. Down databases on the source
      - task: down-databases:{{.SOURCE}}

  # === APP MIGRATION ===
  stateful-app:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      APP: "{{index .MATCH 2}}"
    desc: Migrate stateful app from one cluster to another
    cmds:
      # 1. Backup the app on the source
      - task: backup:project:{{.SOURCE}}:{{.APP}}

      # 2. Down the app on the source
      - task: projects:ni:down:{{.SOURCE}}:{{.APP}}

      # 3. Up the app on the target
      - task: projects:ni:up:{{.TARGET}}:{{.APP}}
    ignore_error: true

  stateless-app:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      APP: "{{index .MATCH 2}}"
    desc: Migrate stateless app from one cluster to another
    cmds:
      # 1. Down the app on the source
      - task: projects:ni:down:{{.SOURCE}}:{{.APP}}

      # 2. Up the app on the target
      - task: projects:ni:up:{{.TARGET}}:{{.APP}}
    ignore_error: true

  apps:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
    desc: Migrate apps from one cluster to another
    deps:
      - for: { var: STATEFUL_APPS }
        task: stateful-app:{{.SOURCE}}:{{.TARGET}}:{{.ITEM}}
      - for: { var: STATELESS_APPS }
        task: stateless-app:{{.SOURCE}}:{{.TARGET}}:{{.ITEM}}

  # === DATABASE MIGRATION ===
  backup-and-up-project:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      PROJECT: "{{index .MATCH 2}}"
    desc: Backup project on the source cluster and up it on the target one
    cmds:
      - task: backup:project:{{.SOURCE}}:{{.PROJECT}}
      - task: projects:ni:up:{{.TARGET}}:{{.PROJECT}}

  backup-and-up-databases:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
    desc: Backup databases on the source cluster and up them on the target one
    deps:
      - for: { var: DATABASES }
        task: backup-and-up-project:{{.SOURCE}}:{{.TARGET}}:{{.ITEM}}

  down-databases:*:
    vars:
      TARGET: "{{index .MATCH 0}}"
    desc: Down databases on the target cluster
    deps:
      - for: { var: DATABASES }
        task: projects:ni:down:{{.TARGET}}:{{.ITEM}}
