version: "3"

tasks:
  cmd:*:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
      CMD: "{{index .MATCH 2}}"
    label: "{{.STACK}}/{{.PROJECT}}: {{.CMD}}"
    desc: Run the pulumi command for the project in the stack
    cmd: pulumi {{.CMD}} -s {{.STACK}} {{.CLI_ARGS}}

  up:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: up {{.STACK}}/{{.PROJECT}}
    desc: Create or update the project in the stack
    cmd: pulumi up -f -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  down:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: down {{.STACK}}/{{.PROJECT}}
    desc: Destroy the project in the stack
    cmd: pulumi down -f -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  refresh:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: refresh {{.STACK}}/{{.PROJECT}}
    desc: Refresh the state of the project in the stack
    cmd: pulumi refresh -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  preview:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: preview {{.STACK}}/{{.PROJECT}}
    desc: Preview the changes for the project in the stack
    cmd: pulumi preview -s {{.STACK}} {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  recreate:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: recreate {{.STACK}}/{{.PROJECT}}
    desc: Recreate the project in the stack
    cmds:
      - task: down:{{.STACK}}:{{.PROJECT}}
      - task: up:{{.STACK}}:{{.PROJECT}}
    ignore_error: true
    interactive: true

  ni:up:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: up {{.STACK}}/{{.PROJECT}}
    desc: Create or update the project in the stack [non-interactive]
    cmd: pulumi up -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  ni:down:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: down {{.STACK}}/{{.PROJECT}}
    desc: Destroy the project in the stack [non-interactive]
    cmd: pulumi down -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  ni:refresh:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: refresh {{.STACK}}/{{.PROJECT}}
    desc: Refresh the state of the project in the stack [non-interactive]
    cmd: pulumi refresh -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
