version: "3"

tasks:
  up:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: up {{.STACK}}/{{.PROJECT}}
    desc: Create or update the "{{.PROJECT}}" project in "{{.STACK}}"
    cmd: pulumi up -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  down:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: down {{.STACK}}/{{.PROJECT}}
    desc: Destroy the "{{.PROJECT}}" project in "{{.STACK}}"
    cmd: pulumi down -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  refresh:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: refresh {{.STACK}}/{{.PROJECT}}
    desc: Refresh the "{{.PROJECT}}" project in "{{.STACK}}"
    cmd: pulumi refresh -s {{.STACK}} -y {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  preview:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: preview {{.STACK}}/{{.PROJECT}}
    desc: Preview the changes for the "{{.PROJECT}}" project in "{{.STACK}}"
    cmd: pulumi preview -s {{.STACK}} {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"
    interactive: true

  non-interactive:up:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: up {{.STACK}}/{{.PROJECT}}
    desc: Create or update the "{{.PROJECT}}" project in "{{.STACK}}" [non-interactive]
    cmd: pulumi up -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  non-interactive:down:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: down {{.STACK}}/{{.PROJECT}}
    desc: Destroy the "{{.PROJECT}}" project in "{{.STACK}}" [non-interactive]
    cmd: pulumi down -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  non-interactive:refresh:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: refresh {{.STACK}}/{{.PROJECT}}
    desc: Refresh the "{{.PROJECT}}" project in "{{.STACK}}" [non-interactive]
    cmd: pulumi refresh -s {{.STACK}} -y --non-interactive {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  recreate:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: recreate {{.STACK}}/{{.PROJECT}}
    desc: Recreate the "{{.PROJECT}}" project in "{{.STACK}}"
    cmds:
      - task: down:{{.STACK}}:{{.PROJECT}}
      - task: up:{{.STACK}}:{{.PROJECT}}
    ignore_error: true
    interactive: true

  init:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: init {{.STACK}}/{{.PROJECT}}
    desc: Initialize the new stack "{{.STACK}}" for the "{{.PROJECT}}" project
    cmd: pulumi stack init {{.STACK}} {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  config:*:*:
    vars:
      STACK: "{{index .MATCH 0}}"
      PROJECT: "{{index .MATCH 1}}"
    label: config {{.STACK}}/{{.PROJECT}}
    desc: Manage the config for the "{{.PROJECT}}" project in "{{.STACK}}"
    cmd: pulumi config {{.CLI_ARGS}} -s {{.STACK}} {{.CLI_ARGS}}
    dir: "{{.PROJECT}}"

  sync-config:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      PROJECT: "{{index .MATCH 2}}"
    label: sync-config {{.PROJECT}} | {{.SOURCE}} -> {{.TARGET}}
    desc: Replace the config of "{{.PROJECT}}" in "{{.TARGET}}" with the config in "{{.SOURCE}}"
    cmd: ../../scripts/sync-stack-config.sh {{.SOURCE}} {{.TARGET}}
    dir: "{{.PROJECT}}"

  migrate:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      PROJECT: "{{index .MATCH 2}}"
    label: migrate {{.PROJECT}} | {{.SOURCE}} -> {{.TARGET}}
    desc: Migrate the "{{.PROJECT}}" project from "{{.SOURCE}}" to "{{.TARGET}}"
    deps:
      - task: non-interactive:up:{{.TARGET}}:{{.PROJECT}}
      - task: non-interactive:down:{{.SOURCE}}:{{.PROJECT}}
    ignore_error: true

  stop:migrate:*:*:*:
    vars:
      SOURCE: "{{index .MATCH 0}}"
      TARGET: "{{index .MATCH 1}}"
      PROJECT: "{{index .MATCH 2}}"
    label: migrate {{.PROJECT}} | {{.SOURCE}} -> {{.TARGET}}
    desc: Migrate the "{{.PROJECT}}" project from "{{.SOURCE}}" to "{{.TARGET}}" with downtime
    cmds:
      - task: non-interactive:down:{{.SOURCE}}:{{.PROJECT}}
      - task: non-interactive:up:{{.TARGET}}:{{.PROJECT}}
    ignore_error: true
