// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * PodUnavailableBudget is the Schema for the podunavailablebudgets API
 */
export class PodUnavailableBudget extends pulumi.CustomResource {
    /**
     * Get an existing PodUnavailableBudget resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PodUnavailableBudget {
        return new PodUnavailableBudget(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:policy.kruise.io/v1alpha1:PodUnavailableBudget';

    /**
     * Returns true if the given object is an instance of PodUnavailableBudget.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PodUnavailableBudget {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PodUnavailableBudget.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"policy.kruise.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"PodUnavailableBudget" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * PodUnavailableBudgetSpec defines the desired state of PodUnavailableBudget
     */
    public readonly spec!: pulumi.Output<outputs.policy.v1alpha1.PodUnavailableBudgetSpec | undefined>;
    /**
     * PodUnavailableBudgetStatus defines the observed state of PodUnavailableBudget
     */
    public readonly status!: pulumi.Output<outputs.policy.v1alpha1.PodUnavailableBudgetStatus | undefined>;

    /**
     * Create a PodUnavailableBudget resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PodUnavailableBudgetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "policy.kruise.io/v1alpha1";
            resourceInputs["kind"] = "PodUnavailableBudget";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PodUnavailableBudget.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PodUnavailableBudget resource.
 */
export interface PodUnavailableBudgetArgs {
    apiVersion?: pulumi.Input<"policy.kruise.io/v1alpha1">;
    kind?: pulumi.Input<"PodUnavailableBudget">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * PodUnavailableBudgetSpec defines the desired state of PodUnavailableBudget
     */
    spec?: pulumi.Input<inputs.policy.v1alpha1.PodUnavailableBudgetSpecArgs>;
    /**
     * PodUnavailableBudgetStatus defines the observed state of PodUnavailableBudget
     */
    status?: pulumi.Input<inputs.policy.v1alpha1.PodUnavailableBudgetStatusArgs>;
}
