// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Ingress is a collection of rules that allow inbound connections to reach the endpoints defined
 * by a backend. An Ingress can be configured to give services externally-reachable URLs, load
 * balance traffic, offer name based virtual hosting, etc.
 *
 * This is heavily based on K8s Ingress https://godoc.org/k8s.io/api/networking/v1beta1#Ingress
 * which some highlighted modifications.
 */
export class Ingress extends pulumi.CustomResource {
    /**
     * Get an existing Ingress resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Ingress {
        return new Ingress(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:networking.internal.knative.dev/v1alpha1:Ingress';

    /**
     * Returns true if the given object is an instance of Ingress.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ingress {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ingress.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"networking.internal.knative.dev/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"Ingress" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec is the desired state of the Ingress.
     * More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    public readonly spec!: pulumi.Output<outputs.networking.v1alpha1.IngressSpec | undefined>;
    /**
     * Status is the current state of the Ingress.
     * More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    public readonly status!: pulumi.Output<outputs.networking.v1alpha1.IngressStatus | undefined>;

    /**
     * Create a Ingress resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IngressArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "networking.internal.knative.dev/v1alpha1";
            resourceInputs["kind"] = "Ingress";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ingress.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Ingress resource.
 */
export interface IngressArgs {
    apiVersion?: pulumi.Input<"networking.internal.knative.dev/v1alpha1">;
    kind?: pulumi.Input<"Ingress">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec is the desired state of the Ingress.
     * More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    spec?: pulumi.Input<inputs.networking.v1alpha1.IngressSpecArgs>;
    /**
     * Status is the current state of the Ingress.
     * More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     */
    status?: pulumi.Input<inputs.networking.v1alpha1.IngressStatusArgs>;
}
