// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { CiliumClusterwideNetworkPolicyArgs } from "./ciliumClusterwideNetworkPolicy";
export type CiliumClusterwideNetworkPolicy = import("./ciliumClusterwideNetworkPolicy").CiliumClusterwideNetworkPolicy;
export const CiliumClusterwideNetworkPolicy: typeof import("./ciliumClusterwideNetworkPolicy").CiliumClusterwideNetworkPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideNetworkPolicy"], () => require("./ciliumClusterwideNetworkPolicy"));

export { CiliumNetworkPolicyArgs } from "./ciliumNetworkPolicy";
export type CiliumNetworkPolicy = import("./ciliumNetworkPolicy").CiliumNetworkPolicy;
export const CiliumNetworkPolicy: typeof import("./ciliumNetworkPolicy").CiliumNetworkPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumNetworkPolicy"], () => require("./ciliumNetworkPolicy"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicy":
                return new CiliumClusterwideNetworkPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNetworkPolicy":
                return new CiliumNetworkPolicy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("cilium", "cilium.io/v2", _module)
