version: "3.9"

services:
  main:
    image: ghcr.io/exeteres/devcontainer/devops
    volumes:
      - ..:/home/dev/workspace:cached
      - ~/.kube/config:/home/dev/.kube/config
      - ~/.pulumi:/home/dev/.pulumi
      - ~/.config/age/key:/home/dev/.config/age/key
      - ~/.ssh/id_ed25519.pub:/home/dev/.ssh/id_ed25519.pub
      - /run/pcscd/pcscd.comm:/run/pcscd/pcscd.comm
    command: sleep infinity

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1200
