version: "3"

tasks:
  bootstrap:
    desc: Bootstrap all stacks in the correct order
    cmds:
      # Infra 0 (Shared)
      - task: shared:bootstrap
      - task: cert-manager:bootstrap
      - task: public-gateway:bootstrap
      - task: vpn-static:bootstrap

      # Infra 1 (Database)
      - task: postgresql:bootstrap
      - task: mariadb:bootstrap

      # Infra 2 (Mail+Identity+Headscale)
      - task: mailu:bootstrap
      - task: zitadel:bootstrap
      - task: headscale:bootstrap

      # Infra 3 (VPN-dependent)
      - task: internal-gateway:bootstrap
      - task: knative:bootstrap
      - task: minio:bootstrap

      # Applications
      - task: kubernetes-dashboard:bootstrap
      - task: ghost:bootstrap
      - task: ghost-ru:bootstrap
      - task: standardnotes:bootstrap
      - task: syncthing:bootstrap
      - task: vaultwarden:bootstrap
      - task: plane:bootstrap
      - task: vpn:bootstrap
      - task: functions:bootstrap
      - task: etebase:bootstrap

  etebase:manage:
    desc: Manage Etebase via Django CLI
    cmd: |
      pod=$(kubectl get pods -l app.kubernetes.io/name=etebase -o jsonpath="{.items[0].metadata.name}" -n etebase)
      kubectl exec -n etebase -c etebase -it $pod -- /etebase/manage.py {{.CLI_ARGS}}

includes:
  cert-manager:
    taskfile: common/Taskfile.yml
    dir: cert-manager
    vars:
      NAME: cert-manager

  etebase:
    taskfile: common/Taskfile.yml
    dir: etebase
    vars:
      NAME: etebase

  functions:
    taskfile: common/Taskfile.yml
    dir: functions
    vars:
      NAME: functions

  ghost:
    taskfile: common/Taskfile.yml
    dir: ghost
    vars:
      NAME: ghost

  ghost-ru:
    taskfile: common/Taskfile.yml
    dir: ghost-ru
    vars:
      NAME: ghost-ru

  headscale:
    taskfile: common/Taskfile.yml
    dir: headscale
    vars:
      NAME: headscale

  internal-gateway:
    taskfile: common/Taskfile.yml
    dir: internal-gateway
    vars:
      NAME: internal-gateway

  knative:
    taskfile: common/Taskfile.yml
    dir: knative
    vars:
      NAME: knative

  kubernetes-dashboard:
    taskfile: common/Taskfile.yml
    dir: kubernetes-dashboard
    vars:
      NAME: kubernetes-dashboard

  mailu:
    taskfile: common/Taskfile.yml
    dir: mailu
    vars:
      NAME: mailu

  mariadb:
    taskfile: common/Taskfile.yml
    dir: mariadb
    vars:
      NAME: mariadb

  minio:
    taskfile: common/Taskfile.yml
    dir: minio
    vars:
      NAME: minio

  plane:
    taskfile: common/Taskfile.yml
    dir: plane
    vars:
      NAME: plane

  postgresql:
    taskfile: common/Taskfile.yml
    dir: postgresql
    vars:
      NAME: postgresql

  public-gateway:
    taskfile: common/Taskfile.yml
    dir: public-gateway
    vars:
      NAME: public-gateway

  shared:
    taskfile: common/Taskfile.yml
    dir: shared
    vars:
      NAME: shared

  standardnotes:
    taskfile: common/Taskfile.yml
    dir: standardnotes
    vars:
      NAME: standardnotes

  syncthing:
    taskfile: common/Taskfile.yml
    dir: syncthing
    vars:
      NAME: syncthing

  vaultwarden:
    taskfile: common/Taskfile.yml
    dir: vaultwarden
    vars:
      NAME: vaultwarden

  vpn:
    taskfile: common/Taskfile.yml
    dir: vpn
    vars:
      NAME: vpn

  vpn-static:
    taskfile: common/Taskfile.yml
    dir: vpn-static
    vars:
      NAME: vpn-static

  zitadel:
    taskfile: common/Taskfile.yml
    dir: zitadel
    vars:
      NAME: zitadel
