version: "3"

tasks:
  bootstrap:
    desc: Bootstrap the {{.NAME}} stack
    cmd: pulumi up -s main --non-interactive -y
  refresh:
    desc: Refresh the {{.NAME}} stack
    cmd: pulumi refresh -s main --non-interactive -y
  destroy:
    desc: Destroy the {{.NAME}} stack
    cmd: pulumi down -s main --non-interactive -y
