// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * BackendLBPolicy provides a way to define load balancing rules
 * for a backend.
 */
export class BackendLBPolicy extends pulumi.CustomResource {
    /**
     * Get an existing BackendLBPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): BackendLBPolicy {
        return new BackendLBPolicy(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:gateway.networking.k8s.io/v1alpha2:BackendLBPolicy';

    /**
     * Returns true if the given object is an instance of BackendLBPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BackendLBPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BackendLBPolicy.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"gateway.networking.k8s.io/v1alpha2" | undefined>;
    public readonly kind!: pulumi.Output<"BackendLBPolicy" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Spec defines the desired state of BackendLBPolicy.
     */
    public readonly spec!: pulumi.Output<outputs.gateway.v1alpha2.BackendLBPolicySpec>;
    /**
     * Status defines the current state of BackendLBPolicy.
     */
    public readonly status!: pulumi.Output<outputs.gateway.v1alpha2.BackendLBPolicyStatus | undefined>;

    /**
     * Create a BackendLBPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BackendLBPolicyArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "gateway.networking.k8s.io/v1alpha2";
            resourceInputs["kind"] = "BackendLBPolicy";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? (args.spec ? pulumi.output(args.spec).apply(inputs.gateway.v1alpha2.backendLBPolicySpecArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BackendLBPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a BackendLBPolicy resource.
 */
export interface BackendLBPolicyArgs {
    apiVersion?: pulumi.Input<"gateway.networking.k8s.io/v1alpha2">;
    kind?: pulumi.Input<"BackendLBPolicy">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Spec defines the desired state of BackendLBPolicy.
     */
    spec?: pulumi.Input<inputs.gateway.v1alpha2.BackendLBPolicySpecArgs>;
    /**
     * Status defines the current state of BackendLBPolicy.
     */
    status?: pulumi.Input<inputs.gateway.v1alpha2.BackendLBPolicyStatusArgs>;
}
