// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * StatefulSet is the Schema for the statefulsets API
 */
export class StatefulSet extends pulumi.CustomResource {
    /**
     * Get an existing StatefulSet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): StatefulSet {
        return new StatefulSet(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:apps.kruise.io/v1beta1:StatefulSet';

    /**
     * Returns true if the given object is an instance of StatefulSet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StatefulSet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StatefulSet.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"apps.kruise.io/v1beta1" | undefined>;
    public readonly kind!: pulumi.Output<"StatefulSet" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * StatefulSetSpec defines the desired state of StatefulSet
     */
    public readonly spec!: pulumi.Output<outputs.apps.v1beta1.StatefulSetSpec | undefined>;
    /**
     * StatefulSetStatus defines the observed state of StatefulSet
     */
    public readonly status!: pulumi.Output<outputs.apps.v1beta1.StatefulSetStatus | undefined>;

    /**
     * Create a StatefulSet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StatefulSetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "apps.kruise.io/v1beta1";
            resourceInputs["kind"] = "StatefulSet";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StatefulSet.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a StatefulSet resource.
 */
export interface StatefulSetArgs {
    apiVersion?: pulumi.Input<"apps.kruise.io/v1beta1">;
    kind?: pulumi.Input<"StatefulSet">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * StatefulSetSpec defines the desired state of StatefulSet
     */
    spec?: pulumi.Input<inputs.apps.v1beta1.StatefulSetSpecArgs>;
    /**
     * StatefulSetStatus defines the observed state of StatefulSet
     */
    status?: pulumi.Input<inputs.apps.v1beta1.StatefulSetStatusArgs>;
}
