// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import {ObjectMeta} from "../meta/v1";

export namespace cilium {
    export namespace v2 {
        /**
         * Status is the status of the Cilium policy rule. 
         *  The reason this field exists in this structure is due a bug in the k8s code-generator that doesn't create a `UpdateStatus` method because the field does not exist in the structure.
         */
        export interface CiliumClusterwideNetworkPolicyStatus {
            conditions?: outputs.cilium.v2.CiliumClusterwideNetworkPolicyStatusConditions[];
            /**
             * DerivativePolicies is the status of all policies derived from the Cilium policy
             */
            derivativePolicies?: {[key: string]: outputs.cilium.v2.CiliumClusterwideNetworkPolicyStatusDerivativePolicies};
        }

        export interface CiliumClusterwideNetworkPolicyStatusConditions {
            /**
             * The last time the condition transitioned from one status to another.
             */
            lastTransitionTime?: string;
            /**
             * A human readable message indicating details about the transition.
             */
            message?: string;
            /**
             * The reason for the condition's last transition.
             */
            reason?: string;
            /**
             * The status of the condition, one of True, False, or Unknown
             */
            status: string;
            /**
             * The type of the policy condition
             */
            type: string;
        }

        /**
         * CiliumNetworkPolicyNodeStatus is the status of a Cilium policy rule for a specific node.
         */
        export interface CiliumClusterwideNetworkPolicyStatusDerivativePolicies {
            /**
             * Annotations corresponds to the Annotations in the ObjectMeta of the CNP that have been realized on the node for CNP. That is, if a CNP has been imported and has been assigned annotation X=Y by the user, Annotations in CiliumNetworkPolicyNodeStatus will be X=Y once the CNP that was imported corresponding to Annotation X=Y has been realized on the node.
             */
            annotations?: {[key: string]: string};
            /**
             * Enforcing is set to true once all endpoints present at the time the policy has been imported are enforcing this policy.
             */
            enforcing?: boolean;
            /**
             * Error describes any error that occurred when parsing or importing the policy, or realizing the policy for the endpoints to which it applies on the node.
             */
            error?: string;
            /**
             * LastUpdated contains the last time this status was updated
             */
            lastUpdated?: string;
            /**
             * Revision is the policy revision of the repository which first implemented this policy.
             */
            localPolicyRevision?: number;
            /**
             * OK is true when the policy has been parsed and imported successfully into the in-memory policy repository on the node.
             */
            ok?: boolean;
        }

        /**
         * Status is the status of the Cilium policy rule
         */
        export interface CiliumNetworkPolicyStatus {
            conditions?: outputs.cilium.v2.CiliumNetworkPolicyStatusConditions[];
            /**
             * DerivativePolicies is the status of all policies derived from the Cilium policy
             */
            derivativePolicies?: {[key: string]: outputs.cilium.v2.CiliumNetworkPolicyStatusDerivativePolicies};
        }

        export interface CiliumNetworkPolicyStatusConditions {
            /**
             * The last time the condition transitioned from one status to another.
             */
            lastTransitionTime?: string;
            /**
             * A human readable message indicating details about the transition.
             */
            message?: string;
            /**
             * The reason for the condition's last transition.
             */
            reason?: string;
            /**
             * The status of the condition, one of True, False, or Unknown
             */
            status: string;
            /**
             * The type of the policy condition
             */
            type: string;
        }

        /**
         * CiliumNetworkPolicyNodeStatus is the status of a Cilium policy rule for a specific node.
         */
        export interface CiliumNetworkPolicyStatusDerivativePolicies {
            /**
             * Annotations corresponds to the Annotations in the ObjectMeta of the CNP that have been realized on the node for CNP. That is, if a CNP has been imported and has been assigned annotation X=Y by the user, Annotations in CiliumNetworkPolicyNodeStatus will be X=Y once the CNP that was imported corresponding to Annotation X=Y has been realized on the node.
             */
            annotations?: {[key: string]: string};
            /**
             * Enforcing is set to true once all endpoints present at the time the policy has been imported are enforcing this policy.
             */
            enforcing?: boolean;
            /**
             * Error describes any error that occurred when parsing or importing the policy, or realizing the policy for the endpoints to which it applies on the node.
             */
            error?: string;
            /**
             * LastUpdated contains the last time this status was updated
             */
            lastUpdated?: string;
            /**
             * Revision is the policy revision of the repository which first implemented this policy.
             */
            localPolicyRevision?: number;
            /**
             * OK is true when the policy has been parsed and imported successfully into the in-memory policy repository on the node.
             */
            ok?: boolean;
        }

    }
}
