version: "3"

includes:
  cert-manager:
    taskfile: Taskfile.crds.yml
    vars:
      NAME: cert-manager
      SOURCES: https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml

  gateway:
    taskfile: Taskfile.crds.yml
    vars:
      NAME: gateway
      SOURCES: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/experimental-install.yaml

  knative:
    taskfile: Taskfile.crds.yml
    vars:
      NAME: knative
      SOURCES: https://github.com/knative/serving/releases/download/knative-v1.14.1/serving-crds.yaml

  cilium:
    taskfile: Taskfile.crds.yml
    vars:
      NAME: cilium
      PREPARE: |
        kubectl get crd -o json | jq '
          .items[] | select(.spec.group == "cilium.io" and ( 
            .metadata.name == "ciliumnetworkpolicies.cilium.io" or
            .metadata.name == "ciliumclusterwidenetworkpolicies.cilium.io"
          )
        )' > cilium.json
      SOURCES: cilium.json
      CLEANUP: rm cilium.json
