name: Dev Container Base

on:
  push:
    branches: ["master"]
    paths:
      - "registry/devcontainer/base/**"
      - ".github/workflows/devcontainer-base.yaml"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/exeteres/devcontainer/base
          cacheFrom: ghcr.io/exeteres/devcontainer/base
          push: always
          subFolder: registry/devcontainer/base
