name: NixOS

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  update-flake:
    name: Update flake
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: cachix/install-nix-action@v27

      - name: Update flake.lock
        run: nix flake update
        working-directory: nixos

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump flake.lock
          branch: master
          commit_options: "--no-verify --signoff"
          file_pattern: nixos/flake.lock
          commit_user_name: Flake Bot
          commit_author: Flake Bot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true
