// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * Configuration represents the "floating HEAD" of a linear history of Revisions.
 * Users create new Revisions by updating the Configuration's spec.
 * The "latest created" revision's name is available under status, as is the
 * "latest ready" revision's name.
 * See also: https://github.com/knative/serving/blob/main/docs/spec/overview.md#configuration
 */
export class Configuration extends pulumi.CustomResource {
    /**
     * Get an existing Configuration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Configuration {
        return new Configuration(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:serving.knative.dev/v1:Configuration';

    /**
     * Returns true if the given object is an instance of Configuration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Configuration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Configuration.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"serving.knative.dev/v1" | undefined>;
    public readonly kind!: pulumi.Output<"Configuration" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * ConfigurationSpec holds the desired state of the Configuration (from the client).
     */
    public readonly spec!: pulumi.Output<outputs.serving.v1.ConfigurationSpec | undefined>;
    /**
     * ConfigurationStatus communicates the observed state of the Configuration (from the controller).
     */
    public readonly status!: pulumi.Output<outputs.serving.v1.ConfigurationStatus | undefined>;

    /**
     * Create a Configuration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ConfigurationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "serving.knative.dev/v1";
            resourceInputs["kind"] = "Configuration";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Configuration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Configuration resource.
 */
export interface ConfigurationArgs {
    apiVersion?: pulumi.Input<"serving.knative.dev/v1">;
    kind?: pulumi.Input<"Configuration">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * ConfigurationSpec holds the desired state of the Configuration (from the client).
     */
    spec?: pulumi.Input<inputs.serving.v1.ConfigurationSpecArgs>;
    /**
     * ConfigurationStatus communicates the observed state of the Configuration (from the controller).
     */
    status?: pulumi.Input<inputs.serving.v1.ConfigurationStatusArgs>;
}
