// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * SidecarSet is the Schema for the sidecarsets API
 */
export class SidecarSet extends pulumi.CustomResource {
    /**
     * Get an existing SidecarSet resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SidecarSet {
        return new SidecarSet(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:apps.kruise.io/v1alpha1:SidecarSet';

    /**
     * Returns true if the given object is an instance of SidecarSet.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SidecarSet {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SidecarSet.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"apps.kruise.io/v1alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"SidecarSet" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * SidecarSetSpec defines the desired state of SidecarSet
     */
    public readonly spec!: pulumi.Output<outputs.apps.v1alpha1.SidecarSetSpec | undefined>;
    /**
     * SidecarSetStatus defines the observed state of SidecarSet
     */
    public readonly status!: pulumi.Output<outputs.apps.v1alpha1.SidecarSetStatus | undefined>;

    /**
     * Create a SidecarSet resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SidecarSetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "apps.kruise.io/v1alpha1";
            resourceInputs["kind"] = "SidecarSet";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SidecarSet.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SidecarSet resource.
 */
export interface SidecarSetArgs {
    apiVersion?: pulumi.Input<"apps.kruise.io/v1alpha1">;
    kind?: pulumi.Input<"SidecarSet">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * SidecarSetSpec defines the desired state of SidecarSet
     */
    spec?: pulumi.Input<inputs.apps.v1alpha1.SidecarSetSpecArgs>;
    /**
     * SidecarSetStatus defines the observed state of SidecarSet
     */
    status?: pulumi.Input<inputs.apps.v1alpha1.SidecarSetStatusArgs>;
}
